# Compose version: https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix
# cmd: sudo docker-compose up -d
version: "3.7"

services:
  my_redis:
    container_name: my_redis
    image: redis:6.0.9
    ports:
      - 6379:6379
    volumes:
      - my_redis_data:/data
    networks:
      - my_net
  my_app:
    container_name: my_app
    image: verlandz/docker-app:1.0
    ports:
      - 8080:8080
    depends_on:
      - my_redis
    environment:
      - REDIS_HOST=my_redis
      - REDIS_PORT=6379
    networks:
      - my_net

networks:
  my_net:
    name: my_net

volumes:
  my_redis_data:
    name: my_redis_data