# cmd : sudo docker build --tag api:latest .

FROM golang:1.11.11
EXPOSE 8082

ENV REDIS_HOST=localhost
ENV REDIS_PORT=6379

WORKDIR $GOPATH/src/github.com/verlandz/docker/api
RUN mkdir -p $PWD
COPY . $PWD

# install dep 
RUN go get -v -u github.com/golang/dep/cmd/dep
# run dep
RUN dep ensure -v -vendor-only

CMD ["sh","-c","go run $PWD/main.go"]