# cmd : sudo docker build --tag web:latest .

FROM golang:1.11.11
EXPOSE 8081

ENV API_HOST=localhost
ENV API_PORT=8082

WORKDIR $GOPATH/src/github.com/verlandz/docker/web
RUN mkdir -p $PWD
COPY . $PWD 
CMD ["sh", "-c", "go run $PWD/main.go"]